import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { AnimatePresence, motion } from "motion/react";
import { CreditCard, Download, Layers3, Pencil, Plus, ReceiptText, ShieldCheck, Sparkles, X } from "lucide-react";
import { subscriptionApi, type AdminBusinessDetail } from "../../api/subscriptions";
import { AssignSubscriptionModal, BusinessPolicyModal, ManualPaymentModal, SubscriptionActionModal } from "./SubscriptionModals";
import { Card, InvoiceRow, Loading, Metric, Status, date, money } from "./SubscriptionUi";

type Tab = "overview" | "invoices" | "payments" | "entitlements";
type ModalKey = "assign" | "payment" | "plan" | "extend" | "discount" | "policy" | null;

export default function AdminSubscriptionDrawer({ detail, loading, onClose, onRefresh }: { detail?: AdminBusinessDetail; loading: boolean; onClose: () => void; onRefresh: () => Promise<any> }) {
  const [tab, setTab] = useState<Tab>("overview"); const [modal, setModal] = useState<ModalKey>(null);
  const suspend = useMutation({ mutationFn: () => detail?.subscription?.status === "suspended" ? subscriptionApi.adminReactivate(detail!.business.id) : subscriptionApi.adminSuspend(detail!.business.id), onSuccess: onRefresh });
  return <div className="fixed inset-0 z-[95] flex justify-end bg-slate-950/30 backdrop-blur-[2px]"><div className="absolute inset-0" onClick={onClose} /><motion.aside initial={{ x: 40, opacity: 0 }} animate={{ x: 0, opacity: 1 }} exit={{ x: 40, opacity: 0 }} className="relative z-10 flex h-full w-full max-w-4xl flex-col bg-slate-50 shadow-2xl">
    <header className="border-b border-slate-200 bg-white px-6 py-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-blue-600">Subscription details</p><h2 className="mt-1 text-lg font-black text-slate-950">{detail?.business.name || "Business"}</h2><p className="mt-1 text-[10px] text-slate-500">{detail?.business.email || ""}</p></div><button onClick={onClose} className="rounded-xl p-2 text-slate-400 hover:bg-slate-50"><X className="h-4 w-4" /></button></div></header>
    {loading || !detail ? <div className="p-6"><Loading /></div> : <>
      <div className="border-b border-slate-200 bg-white px-6"><nav className="flex gap-1 overflow-x-auto">{(["overview","invoices","payments","entitlements"] as Tab[]).map((key) => <button key={key} onClick={() => setTab(key)} className={`border-b-2 px-3 py-3 text-[10px] font-black uppercase tracking-wider ${tab === key ? "border-blue-600 text-blue-700" : "border-transparent text-slate-400"}`}>{key}</button>)}</nav></div>
      <main className="flex-1 overflow-y-auto p-6">{!detail.subscription ? <Unassigned detail={detail} onAssign={() => setModal("assign")} /> : <>
        {tab === "overview" && <Overview detail={detail} setModal={setModal} suspended={suspend.isPending} onToggleSuspend={() => suspend.mutate()} />}
        {tab === "invoices" && <Card title="Invoices">{detail.invoices.length ? <div className="divide-y divide-slate-100">{detail.invoices.map((invoice) => <InvoiceRow key={invoice.id} invoice={invoice} onDownload={() => subscriptionApi.downloadInvoice(invoice.id)} />)}</div> : <EmptyLine text="No invoices." />}</Card>}
        {tab === "payments" && <Payments detail={detail} onRecord={() => setModal("payment")} />}
        {tab === "entitlements" && <Entitlements detail={detail} onRefresh={onRefresh} />}
      </>}</main>
      <AnimatePresence>{modal === "assign" && <AssignSubscriptionModal detail={detail} onClose={() => setModal(null)} onSaved={onRefresh} />}{modal === "payment" && <ManualPaymentModal detail={detail} onClose={() => setModal(null)} onSaved={onRefresh} />}{modal === "policy" && <BusinessPolicyModal detail={detail} onClose={() => setModal(null)} onSaved={onRefresh} />}{(modal === "plan" || modal === "extend" || modal === "discount") && <SubscriptionActionModal type={modal} detail={detail} onClose={() => setModal(null)} onSaved={onRefresh} />}</AnimatePresence>
    </>}
  </motion.aside></div>;
}

function Unassigned({ detail, onAssign }: { detail: AdminBusinessDetail; onAssign: () => void }) { return <div className="rounded-3xl border border-dashed border-slate-200 bg-white p-10 text-center"><CreditCard className="mx-auto h-7 w-7 text-slate-400" /><h3 className="mt-3 text-sm font-black text-slate-900">No subscription assigned</h3><p className="mt-1 text-xs text-slate-500">Assign a plan, cycle and optional trial to activate the commercial lifecycle.</p><button onClick={onAssign} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-black text-white"><Plus className="h-4 w-4" />Assign subscription</button></div>; }

function Overview({ detail, setModal, suspended, onToggleSuspend }: { detail: AdminBusinessDetail; setModal: (m: ModalKey) => void; suspended: boolean; onToggleSuspend: () => void }) {
  const sub = detail.subscription!; const plan = sub.Plan || detail.plans.find((p) => p.id === sub.planId); const outstanding = detail.invoices.reduce((sum, i) => sum + Number(i.outstandingAmount || 0), 0);
  return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Sparkles} label="Plan" value={plan?.name || "—"} /><Metric icon={ShieldCheck} label="Status" value={<Status status={sub.status} compact />} /><Metric icon={ReceiptText} label="Outstanding" value={money(outstanding, plan?.currency)} /><Metric icon={CreditCard} label="Renewal" value={date(sub.currentPeriodEnd)} /></div>
    <div className="grid gap-5 lg:grid-cols-2"><Card title="Commercial summary"><Line label="Billing cycle" value={sub.billingCycle} /><Line label="Current period" value={`${date(sub.currentPeriodStart)} — ${date(sub.currentPeriodEnd)}`} /><Line label="Included seats" value={String(plan?.includedSeats || 0)} /><Line label="Extra seat" value={money(plan?.extraSeatPrice, plan?.currency)} /><Line label="Credit balance" value={money(sub.creditBalance, plan?.currency)} /><Line label="Discount" value={`${Number(sub.discountPercent || 0)}%`} /></Card><Card title="Effective access policy"><Line label="Grace days" value={String(detail.policy.effective.gracePeriodDays)} /><Line label="Grace access" value={String(detail.policy.effective.graceAccessMode).replace(/_/g," ")} /><Line label="Expired access" value={String(detail.policy.effective.expiredAccessMode).replace(/_/g," ")} /><Line label="Retention" value={`${detail.policy.effective.retentionDays} days`} /><Line label="Downgrade" value={String(detail.policy.effective.downgradePolicy).replace(/_/g," ")} /></Card></div>
    <Card title="Platform Admin controls"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{[["plan","Change plan",Pencil],["extend","Grant free days",Plus],["discount","Apply discount",CreditCard],["payment","Record payment",ReceiptText],["policy","Lifecycle policy",ShieldCheck]] .map(([key,label,Icon]: any) => <button key={key} onClick={() => setModal(key)} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-left text-[11px] font-black text-slate-700 hover:border-blue-200 hover:bg-blue-50/40 hover:text-blue-700"><Icon className="h-4 w-4" />{label}</button>)}<button onClick={onToggleSuspend} disabled={suspended} className={`flex items-center gap-2 rounded-xl border px-3.5 py-3 text-left text-[11px] font-black ${sub.status === "suspended" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-rose-200 bg-rose-50 text-rose-700"}`}><ShieldCheck className="h-4 w-4" />{sub.status === "suspended" ? "Reactivate" : "Suspend"}</button></div></Card>
  </div>;
}

function Payments({ detail, onRecord }: { detail: AdminBusinessDetail; onRecord: () => void }) { return <Card title="Payments"><div className="mb-3 flex justify-end"><button onClick={onRecord} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-3.5 py-2 text-[10px] font-black text-white"><Plus className="h-3.5 w-3.5" />Record payment</button></div>{detail.payments.length ? <div className="grid gap-3 md:grid-cols-2">{detail.payments.map((payment) => <div key={payment.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex items-start justify-between"><div><p className="text-sm font-black text-slate-900">{money(payment.amount, payment.currency)}</p><p className="mt-1 text-[10px] text-slate-500">{payment.providerReference || "Manual"} · {date(payment.paidAt)}</p></div><Status status={payment.status} compact /></div><div className="mt-3 flex flex-wrap gap-3"><button onClick={() => subscriptionApi.downloadPaymentReceipt(payment.id)} className="inline-flex items-center gap-1 text-[10px] font-black text-blue-700"><Download className="h-3 w-3" />System receipt</button>{payment.metadata?.receiptPath && <button onClick={() => subscriptionApi.downloadOriginalReceipt(payment.id)} className="text-[10px] font-black text-slate-600">Original attachment</button>}</div></div>)}</div> : <EmptyLine text="No payments." />}</Card>; }

function Entitlements({ detail, onRefresh }: { detail: AdminBusinessDetail; onRefresh: () => Promise<any> }) {
  return <div className="space-y-5"><Card title="Runtime modules"><div className="grid gap-2 sm:grid-cols-2">{detail.modules.map((module) => <ModuleRow key={module.moduleKey} businessId={detail.business.id} row={module} onRefresh={onRefresh} />)}</div></Card><Card title="Feature limits"><div className="space-y-2">{detail.features.map((feature) => <FeatureRow key={feature.featureId} businessId={detail.business.id} row={feature} onRefresh={onRefresh} />)}</div></Card></div>;
}

function ModuleRow({ businessId, row, onRefresh }: any) { const enabled = row.status === "active"; const mutation = useMutation({ mutationFn: () => subscriptionApi.adminModuleOverride(businessId, row.moduleKey, { enabled: !enabled, moduleName: row.moduleName }), onSuccess: onRefresh }); return <button onClick={() => mutation.mutate()} disabled={mutation.isPending} className={`flex items-center justify-between rounded-xl border px-3 py-2.5 text-left ${enabled ? "border-blue-200 bg-blue-50/50" : "border-slate-200 bg-white"}`}><span className="flex items-center gap-2 text-[11px] font-black text-slate-700"><Layers3 className="h-3.5 w-3.5" />{row.moduleName || row.moduleKey}</span><span className={`text-[9px] font-black uppercase ${enabled ? "text-blue-700" : "text-slate-400"}`}>{enabled ? "Active" : "Off"}</span></button>; }
function FeatureRow({ businessId, row, onRefresh }: any) { const [limit, setLimit] = useState(row.limitValue == null ? "" : String(row.limitValue)); const mutation = useMutation({ mutationFn: () => subscriptionApi.adminFeatureOverride(businessId, row.featureId, { isEnabled: row.isEnabled, limitValue: limit === "" ? null : Number(limit), limitPeriod: row.limitPeriod, overageUnitPrice: Number(row.overageUnitPrice || 0) }), onSuccess: onRefresh }); return <div className="flex flex-col gap-2 rounded-xl border border-slate-100 p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[11px] font-black text-slate-800">{row.feature?.name || row.featureId}</p><p className="text-[9px] text-slate-400">{row.isEnabled ? "Enabled" : "Disabled"} · {row.limitPeriod || "lifetime"}</p></div><div className="flex items-center gap-2"><input value={limit} onChange={(e) => setLimit(e.currentTarget.value)} type="number" min={0} placeholder="Unlimited" className="w-28 rounded-lg border border-slate-200 bg-slate-50 px-2.5 py-1.5 text-[10px] font-bold outline-none" /><button onClick={() => mutation.mutate()} disabled={mutation.isPending} className="rounded-lg bg-slate-900 px-3 py-1.5 text-[9px] font-black text-white">Override</button></div></div>; }
function Line({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4 border-b border-slate-100 py-3 last:border-0"><span className="text-[10px] font-bold text-slate-400">{label}</span><span className="text-right text-[11px] font-black capitalize text-slate-800">{value}</span></div>; }
function EmptyLine({ text }: { text: string }) { return <p className="py-8 text-center text-xs font-medium text-slate-400">{text}</p>; }
