import React, { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { subscriptionApi, type AccessMode, type AdminBusinessDetail, type SubscriptionPolicy } from "../../api/subscriptions";
import { ACCESS_OPTIONS, Actions, ErrorText, Field, Modal, control } from "./SubscriptionUi";

type Refresh = () => Promise<any>;

export function AssignSubscriptionModal({ detail, onClose, onSaved }: { detail: AdminBusinessDetail; onClose: () => void; onSaved: Refresh }) {
  const [planId, setPlanId] = useState(detail.plans[0]?.id || "");
  const [billingCycle, setBillingCycle] = useState<"monthly" | "yearly">("monthly");
  const [trialDays, setTrialDays] = useState(0);
  const mutation = useMutation({ mutationFn: () => subscriptionApi.adminAssign(detail.business.id, { planId, billingCycle, trialDays }), onSuccess: async () => { await onSaved(); onClose(); } });
  return <Modal title={`Assign subscription · ${detail.business.name}`} onClose={onClose}><div className="grid gap-4"><Field label="Plan"><select className={control} value={planId} onChange={(e) => setPlanId(e.target.value)}>{detail.plans.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Billing cycle"><select className={control} value={billingCycle} onChange={(e) => setBillingCycle(e.target.value as any)}><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></Field><Field label="Trial days"><input className={control} type="number" min={0} value={trialDays} onChange={(e) => setTrialDays(Number(e.target.value))} /></Field>{mutation.error && <ErrorText error={mutation.error} />}</div><Actions onClose={onClose} onSave={() => mutation.mutate()} busy={mutation.isPending} label="Assign subscription" /></Modal>;
}

export function ManualPaymentModal({ detail, onClose, onSaved }: { detail: AdminBusinessDetail; onClose: () => void; onSaved: Refresh }) {
  const openInvoices = detail.invoices.filter((i) => Number(i.outstandingAmount ?? i.totalAmount) > 0 && i.status !== "paid" && i.status !== "void");
  const [invoiceId, setInvoiceId] = useState(openInvoices[0]?.id || "");
  const selected = openInvoices.find((i) => i.id === invoiceId);
  const [amount, setAmount] = useState(Number(selected?.outstandingAmount ?? selected?.totalAmount ?? 0));
  const [paidAt, setPaidAt] = useState(new Date().toISOString().slice(0, 10));
  const [reference, setReference] = useState(""); const [notes, setNotes] = useState(""); const [receipt, setReceipt] = useState<File | null>(null);
  useEffect(() => { const invoice = openInvoices.find((i) => i.id === invoiceId); if (invoice) setAmount(Number(invoice.outstandingAmount ?? invoice.totalAmount)); }, [invoiceId]);
  const mutation = useMutation({ mutationFn: () => subscriptionApi.adminRecordPayment(detail.business.id, { invoiceId, amount, paidAt, providerReference: reference, notes, receipt }), onSuccess: async () => { await onSaved(); onClose(); } });
  return <Modal title={`Record manual payment · ${detail.business.name}`} onClose={onClose}><div className="space-y-4">{openInvoices.length ? <><Field label="Invoice"><select className={control} value={invoiceId} onChange={(e) => setInvoiceId(e.target.value)}>{openInvoices.map((i) => <option key={i.id} value={i.id}>{i.invoiceNumber} · {Number(i.outstandingAmount ?? i.totalAmount).toLocaleString()} {i.currency}</option>)}</select></Field><div className="grid gap-4 md:grid-cols-2"><Field label="Amount"><input className={control} type="number" min={0} step="0.01" value={amount} onChange={(e) => setAmount(Number(e.target.value))} /></Field><Field label="Payment date"><input className={control} type="date" value={paidAt} onChange={(e) => setPaidAt(e.target.value)} /></Field></div><Field label="Reference"><input className={control} value={reference} onChange={(e) => setReference(e.target.value)} placeholder="Bank reference / transfer ID" /></Field><Field label="Receipt (PNG, JPG, PDF)"><input className={control} type="file" accept="image/png,image/jpeg,application/pdf" onChange={(e) => setReceipt(e.target.files?.[0] || null)} /></Field><Field label="Notes"><textarea className={`${control} min-h-20 resize-none`} value={notes} onChange={(e) => setNotes(e.target.value)} /></Field></> : <p className="rounded-2xl bg-slate-50 p-5 text-xs font-semibold text-slate-500">There is no open invoice to pay.</p>}{mutation.error && <ErrorText error={mutation.error} />}</div>{openInvoices.length > 0 && <Actions onClose={onClose} onSave={() => mutation.mutate()} busy={mutation.isPending} label="Confirm payment" />}</Modal>;
}

export function SubscriptionActionModal({ type, detail, onClose, onSaved }: { type: "plan" | "extend" | "discount"; detail: AdminBusinessDetail; onClose: () => void; onSaved: Refresh }) {
  const [planId, setPlanId] = useState(detail.subscription?.planId || detail.plans[0]?.id || ""); const [force, setForce] = useState(false); const [days, setDays] = useState(30); const [discount, setDiscount] = useState(Number(detail.subscription?.discountPercent || 0));
  const mutation = useMutation({ mutationFn: () => type === "plan" ? subscriptionApi.adminChangePlan(detail.business.id, planId, force) : type === "extend" ? subscriptionApi.adminExtend(detail.business.id, days) : subscriptionApi.adminSetDiscount(detail.business.id, discount), onSuccess: async () => { await onSaved(); onClose(); } });
  const title = type === "plan" ? "Change plan" : type === "extend" ? "Grant free days" : "Apply subscription discount";
  return <Modal title={title} onClose={onClose}><div className="space-y-4">{type === "plan" ? <><Field label="Target plan"><select className={control} value={planId} onChange={(e) => setPlanId(e.target.value)}>{detail.plans.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><label className="flex items-start gap-3 rounded-2xl border border-slate-100 p-4"><input type="checkbox" checked={force} onChange={(e) => setForce(e.target.checked)} /><div><p className="text-xs font-black text-slate-900">Administrative override</p><p className="mt-1 text-[10px] leading-4 text-slate-500">Off = normal prorated billing. On = apply immediately without waiting for payment.</p></div></label></> : type === "extend" ? <Field label="Days"><input className={control} type="number" min={1} value={days} onChange={(e) => setDays(Number(e.target.value))} /></Field> : <Field label="Discount percent"><input className={control} type="number" min={0} max={100} value={discount} onChange={(e) => setDiscount(Number(e.target.value))} /></Field>}{mutation.error && <ErrorText error={mutation.error} />}</div><Actions onClose={onClose} onSave={() => mutation.mutate()} busy={mutation.isPending} label={type === "plan" ? "Change plan" : type === "extend" ? "Extend" : "Save discount"} /></Modal>;
}

export function BusinessPolicyModal({ detail, onClose, onSaved }: { detail: AdminBusinessDetail; onClose: () => void; onSaved: Refresh }) {
  const effective = detail.policy.effective; const source = detail.policy.business || effective;
  const [draft, setDraft] = useState<SubscriptionPolicy>({ gracePeriodDays: source.gracePeriodDays, graceAccessMode: source.graceAccessMode, expiredAccessMode: source.expiredAccessMode, retentionDays: source.retentionDays, downgradePolicy: source.downgradePolicy, autoRenew: source.autoRenew });
  const mutation = useMutation({ mutationFn: () => subscriptionApi.adminSetBusinessPolicy(detail.business.id, draft), onSuccess: async () => { await onSaved(); onClose(); } });
  return <PolicyEditor title={`Lifecycle policy · ${detail.business.name}`} draft={draft} setDraft={setDraft} onClose={onClose} onSave={() => mutation.mutate()} busy={mutation.isPending} error={mutation.error} />;
}

export function PlatformPolicyModal({ onClose, onSaved }: { onClose: () => void; onSaved: Refresh }) {
  const query = useQuery({ queryKey: ["platform-subscription-policy"], queryFn: subscriptionApi.adminPlatformPolicy });
  const [draft, setDraft] = useState<SubscriptionPolicy>({});
  useEffect(() => { const source = query.data?.effective || query.data?.platform; if (source) setDraft({ gracePeriodDays: source.gracePeriodDays ?? 7, graceAccessMode: source.graceAccessMode ?? "read_only", expiredAccessMode: source.expiredAccessMode ?? "billing_only", retentionDays: source.retentionDays ?? 90, downgradePolicy: source.downgradePolicy ?? "block", autoRenew: source.autoRenew ?? false }); }, [query.data]);
  const mutation = useMutation({ mutationFn: () => subscriptionApi.adminSetPlatformPolicy(draft), onSuccess: async () => { await onSaved(); onClose(); } });
  return <PolicyEditor title="Platform subscription defaults" draft={draft} setDraft={setDraft} onClose={onClose} onSave={() => mutation.mutate()} busy={mutation.isPending || query.isLoading} error={mutation.error} />;
}

function PolicyEditor({ title, draft, setDraft, onClose, onSave, busy, error }: { title: string; draft: SubscriptionPolicy; setDraft: React.Dispatch<React.SetStateAction<SubscriptionPolicy>>; onClose: () => void; onSave: () => void; busy: boolean; error: any }) {
  const update = (patch: Partial<SubscriptionPolicy>) => setDraft((d) => ({ ...d, ...patch }));
  return <Modal title={title} onClose={onClose}><div className="grid gap-4 md:grid-cols-2"><Field label="Grace period days"><input className={control} type="number" min={0} value={draft.gracePeriodDays ?? 0} onChange={(e) => update({ gracePeriodDays: Number(e.target.value) })} /></Field><Field label="Grace access"><select className={control} value={draft.graceAccessMode || "read_only"} onChange={(e) => update({ graceAccessMode: e.target.value as AccessMode })}>{ACCESS_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></Field><Field label="Expired access"><select className={control} value={draft.expiredAccessMode || "billing_only"} onChange={(e) => update({ expiredAccessMode: e.target.value as AccessMode })}>{ACCESS_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></Field><Field label="Retention days"><input className={control} type="number" min={0} value={draft.retentionDays ?? 0} onChange={(e) => update({ retentionDays: Number(e.target.value) })} /></Field><Field label="Downgrade policy"><select className={control} value={draft.downgradePolicy || "block"} onChange={(e) => update({ downgradePolicy: e.target.value as any })}><option value="block">Block downgrade</option><option value="allow_with_warning">Allow with warning</option><option value="restrict_new">Allow, restrict new usage</option></select></Field><Field label="Auto renew"><button onClick={() => update({ autoRenew: !draft.autoRenew })} className={`flex w-full items-center justify-between rounded-xl border px-3.5 py-2.5 text-xs font-bold ${draft.autoRenew ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-slate-200 bg-slate-50 text-slate-600"}`}><span>{draft.autoRenew ? "Enabled" : "Disabled (manual now)"}</span><span className={`h-5 w-9 rounded-full p-0.5 ${draft.autoRenew ? "bg-emerald-500" : "bg-slate-300"}`}><span className={`block h-4 w-4 rounded-full bg-white transition ${draft.autoRenew ? "translate-x-4" : ""}`} /></span></button></Field>{error && <div className="md:col-span-2"><ErrorText error={error} /></div>}</div><Actions onClose={onClose} onSave={onSave} busy={busy} label="Save policy" /></Modal>;
}
